export default {
  products: [
    {
      _id: "1",
      name: "Millenia",
      category: "watch",
      image: "/images/product-1.jpg",
      price: 59,
      brand: "Tiffany & Co.",
      rating: 4.5,
      numReviews: 10,
      countInStock: 1,
    },
    {
      _id: "2",
      name: "Twist Rows ring, White, Rhodium plated",
      category: "ring",
      image: "/images/product-2.jpg",
      price: 70,
      brand: "Tiffany & Co.",
      rating: 5,
      numReviews: 51,
    },
    {
      _id: "3",
      name: "Attract Ring Set, White, Rhodium plated",
      category: "ring",
      image: "/images/product-3.jpg",
      price: 59,
      brand: "Tiffany & Co.",
      rating: 4,
      numReviews: 45,
    },
    {
      _id: "4",
      name: "My Princess - Gold, Rhodium plated",
      category: "watch",
      image: "/images/product-4.jpg",
      price: 90,
      brand: "Tiffany & Co.",
      rating: 2.5,
      numReviews: 198,
      countInStock: 6,
    },
    {
      _id: "5",
      name: "Tennis Deluxe Bracelet, White, Rhodium plated",
      category: "ring",
      image: "/images/product-5.jpg",
      price: 119,
      brand: "Tiffany & Co.",
      rating: 3.5,
      numReviews: 89,
      countInStock: 6,
    },
    {
      _id: "6",
      name: "Attract Cocktail Ring, Green, Rhodium plated",
      category: "tiala",
      image: "/images/product-6.jpg",
      price: 85,
      brand: "Tiffany & Co.",
      rating: 4.5,
      numReviews: 45,
      countInStock: 6,
    },
  ],
};
